//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaDatabase.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partition()
        {
            this.Volumes = new HashSet<Volume>();
        }
    
        public int Id { get; set; }
        public string Caption { get; set; }
        public int DiskIndex { get; set; }
        public int PartitionIndex { get; set; }
    
        public virtual Medium Medium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volume> Volumes { get; set; }
    }
}
